version: 0.0
os: linux
files:
    - source: /
      destination: /home/ubuntu/do_it_django/
file_exists_behavior: OVERWRITE

permissions:
    - object: /home/ubuntu/do_it_django
      pattern: '**'
      owner: root
      group: root

hooks:
    AfterInstall:
        - location: scripts/after-deploy.sh
          timeout: 60000
          runas: root