# Generated by Django 5.1.3 on 2024-11-26 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="editor",
        ),
        migrations.RemoveField(
            model_name="post",
            name="email",
        ),
    ]
