# Generated by Django 5.1.3 on 2024-11-26 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_category_newspost_delete_post"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="Press",
        ),
        migrations.AlterModelOptions(
            name="press",
            options={"verbose_name_plural": "Presses"},
        ),
    ]
