# Generated by Django 5.1.3 on 2024-11-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_tag_post_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tag",
            field=models.ManyToManyField(blank=True, to="blog.tag"),
        ),
    ]
